### PR TITLE
Changed the ui of the question box on the top questions page

### PR DESCRIPTION
**Pull request by lokevin88**
- Combined the username and date on the same line
- Added a switch statement to convert the month number to text
- Added a switch statement to add suffix for the days
- Made the question bigger

### CODE REVIEW

**Comment by lokevin88** [comment]
Need to replace var by let or const

**Comment by dobrovv** [comment]
@lokevin88 django returns date in ISO 8601 format ( YYYY-MM-DDTHH:MM:SS ) it should be easy to parse with javascript. You can try Date(date_created) instead of parsing it manually.

**Comment by lokevin88** [comment]
@dobrovv Thanks, but I actually want the full name of the month and the suffix for the days. I think Date(date_created) can't give me the full month name, if I am not mistaken.

**Comment by dobrovv** [comment]
@lokevin88 Ah ok makes sense. Sorry, I thought you can specify what Date.toString() outputs.

**Comment by lokevin88** [comment]
Yeah, it can't do what I want, but thank you

**Pull request merged**
