### PR TITLE
User registration/authentication Issue #20

### PR DESCRIPTION
**Pull request by dobrovv**
- Backend can now register and authenticate users
- Made several new url endpoints for communication with the frontend
- Stored users can now be listed at api/user/
- The currently logged in user can be retrieved at api/user/me/

### CODE REVIEW

**Comment by chimano** [comment]
Does your code check to see if the username is unique when registering?

**Comment by dobrovv** [comment]
Not explicitly. The db throws an exception if the key is already present.
I am getting as the response {"error": "IntegrityError('UNIQUE constraint failed: auth_user.username',)"} 

It's probably a bad way to validate data but is very simple.  Should I add a rest-framework serializer?

**Comment by dobrovv** [comment]
I have added the check.

**Comment by alireza260** [comment]
Nice job!

**Pull request merged**
