### PR TITLE
Tag support for backend user story #92 task #141

### PR DESCRIPTION
**Pull request by dobrovv**
Tag support for backend user story #92 task #141

- created Tag model
- added tags field to the Question model
- added optional tags parameter in POST api/question/
- added optional filtering by tags to GET api/question/
- changed QuestionSerializer to include tags
- added api/tags/ endpoint to list the existing tags
- added blank=True fields (for admin panel)
- added tests for QuestionView and TagView

### CODE REVIEW

**Comment by chimano** [comment]
@GuiWukai Is there any reason why the component rendering failed?

**Comment by dobrovv** [comment]
I have not changed the frontend but this branch was behind the master.

**Comment by GuiWukai** [comment]
I'm getting this error:
GET /api/question/?order=desc&limit=36&sort=date_created HTTP/1.1" 500 185016
Do I have to delete and recreate my database?

**Comment by dobrovv** [comment]
@GuiWukai have you run manage.py makemigrations and migrate? All the parameters I have added are optional I hope we won't need to delete dbs. Can you send me the response from the Network tab?

**Comment by GuiWukai** [comment]
kk thanks! I just did that. Now it works perfectly! Im gonna review the code

**Pull request merged**
